name: Publish NPM Semantic Release

on:
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository == 'yikoyu/vuetify-pro-tiptap' }}
    uses: yikoyu/workflows/.github/workflows/publish-npm-semantic-release.yml@main
    secrets:
      github-token: ${{ secrets.ACCESS_TOKEN }}
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    with:
      build-command: pnpm build:lib
